### PR TITLE
Add Xib file support

### PR DESCRIPTION
**Pull request by b9zhengaoxing**
Add Xib file support, add  a judge to _setup function , jump out of the
_setup - layoutSubviews death cycle.

添加xib文件支持，对_setup 函数添加判断，跳出_setup ——  layoutSubviews 死循环。

### CODE REVIEW

**Comment by xiekw2010** [comment]
Hi @b9zhengaoxing Thanks for your pull request. The fix warning and supporting xib idea is good.
But I suggest, fix warning should be like this:

```
- (instancetype)init {
    self = [super initWithFrame:CGRectZero];
    if (self) {
        [self commonInit];
    }

    return self;
}

- (id)initWithFrame:(CGRect)frame {
    self = [super initWithFrame:CGRectZero];
    if (self) {
        [self commonInit];
    }

    return self;
}

- (instancetype)initWithCoder:(NSCoder *)aDecoder {
    self = [super initWithCoder:aDecoder];
    if (self) {
        [self commonInit];
    }

    return self;
}

- (void)commonInit {
    _isiOS7 = ([[[UIDevice currentDevice] systemVersion] compare:@"7.0"] != NSOrderedAscending);
    self.arrowSize = CGSizeMake(11.0, 9.0);
    self.cornerRadius = 5.0;
    self.backgroundColor = [UIColor whiteColor];
    self.animationIn = 0.4;
    self.animationOut = 0.3;
    self.animationSpring = YES;
    self.sideEdge = 10.0;
    self.maskType = DXPopoverMaskTypeBlack;
    self.betweenAtViewAndArrowHeight = 4.0;
    self.applyShadow = YES;
}
```

Your fixing the `layoutSubviews` death cycle is a nice try, but the hard code works not well, you can check it on taping the green hello button.

**Comment by b9zhengaoxing** [comment]
hello xiekw2010 thank you for your detailed suggestion. Your code for fixing the warning  is great! 

And I changed xibfile support code like this:

```
@implementation DXPopover {
    BOOL _isiOS7;
    BOOL _breakDeathCycle;
}

- (void)show {
    _breakDeathCycle=YES;
    .............
}

- (void)_setup {
    if (_breakDeathCycle==NO) {
        return;
    }
    ...........

    _breakDeathCycle=NO;
}
```

**Comment by xiekw2010** [comment]
@b9zhengaoxing Your coding for breaking the death cycle works. But the code will be more readable for the instance var  `_breakDeathCycle` replaced by some name like `_setNeedsReset` or something like this.

I will merge your great xib support  after you changing the instance var.

**Comment by b9zhengaoxing** [comment]
Hi @xiekw2010，the instance var is changed now.

Have a good day.

**Pull request merged**
